name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
      
  build:

    runs-on: ubuntu-latest
    env:
      tag1: '$(date +%s)'

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zendto:${{ env.tag1 }} --tag zendto:latest
    
    - name: Login to DockerHub
      if: GitHub.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push tagged image to dockerhub repository
      run: docker push fle108/zendto:$tag
    
    - name: Push latest image to dockerhub repository
      run: docker push fle108/zendto:latest
